all:
	i686-w64-mingw32-gcc -o your_program.exe windows.c \
	-I../SDL2-2.28.4/i686-w64-mingw32/include \
	-L../SDL2-2.28.4/i686-w64-mingw32/lib -Llib \
	-lSDL2 -lm -static-libgcc -static-libstdc++ -mwindows
